### ISSUE TITLE
Attribute error: 'nonetype' object has no attribute 'keys'

### ISSUE THREAD

**Issue by PrakharPrashantSingh** [ArunMichaelDsouza/tensorflow-image-detection#11]
this error is coming after downloading inception package at command Retrain.py

**Comment by ArunMichaelDsouza** [comment]
Can you please tell me which version of Python and Tensorflow you are running?

**Comment by PrakharPrashantSingh** [comment]
I resolved this issue, my python verson 3.6 and tensorflow is latest version, sorry forgot to  query, the error occured due to path error

**Comment by PrakharPrashantSingh** [comment]
The program was not behaving in the right way as it is supposed to be, it didn't create a  folder named tf_"data" or something, inspite of that in the temp directory, .pb model and attribute text file were changed after retaining, so i changed path in the final .py executable file and it ran, took around 2-3 hrs extra but worked!!! 
Thanks for making this simple code!!

**Comment by ArunMichaelDsouza** [comment]
Sure, not a problem! Great that you were able to make it work.

**Comment by PrakharPrashantSingh** [comment]
if this error again occur, try this:
python F:\Tensorflow\retrain.py --image_dir C:\training_data --how_many_training_steps 500 --model_dir F:\Tensorflow\inception --output_graph=F:\Tensorflow\retrained_graph.pb --output_labels=F:\Tensorflow\retrained_labels.txt
