### ISSUE TITLE
Regarding displayed results

### ISSUE THREAD

**Issue by PrakharPrashantSingh** [ArunMichaelDsouza/tensorflow-image-detection#13]
Sir, one question i am having, is there any way to remove the probabilities (in result) lesser than 0.00__? 
I mean to say, to remove results which have very least value, is there any way?

**Comment by ArunMichaelDsouza** [comment]
Hi @PrakharPrashantSingh, you can view the source code of the [classify.py](https://github.com/ArunMichaelDsouza/tensorflow-image-detection/blob/master/classify.py) script that makes the predictions. You can edit this script to remove all the probabilities that are less than 0.00.

**Comment by PrakharPrashantSingh** [comment]
so i need to modify these lines, right?

# Sort to show labels of first prediction in order of confidence
        top_k = predictions[0].argsort()[-len(predictions[0]):][::-1]
        
        for node_id in top_k:
            human_string = label_lines[node_id]
            score = predictions[0][node_id]
            print('%s (score = %.5f)' % (human_string, score))

can u please tell me what to change to remove results having 0.00..... i only want to have results greater than 0.01

**Comment by ArunMichaelDsouza** [comment]
Yes, these are the correct lines. It's pretty simple if you'd like to only display results having a score greater than ``0.01`` in the current result set -
```
if round(score, 2) > 0.01:
    print('%s (score = %.5f)' % (human_string, score))
```

**Comment by PrakharPrashantSingh** [comment]
Thank You sir! However i figured out one more way i.e. to write the output of DOS into a file and show only 1st line as i don't really know python, my coding language is C++. But Thanks for help!

**Comment by ArunMichaelDsouza** [comment]
Great! not a problem.
