### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SurenderMohanRaghav** [ArunMichaelDsouza/tensorflow-image-detection#4]
File "retrain.py", line 817, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by ArunMichaelDsouza** [comment]
Is the image training dataset provided in the specified manner ?

**Comment by SurenderMohanRaghav** [comment]
Yes, I provided.

**Comment by ArunMichaelDsouza** [comment]
I mean to say that the images need to be present in the ``training_dataset`` directory with folder names depicting the ``labels`` for individual training data sets. Only after the proper setup the transfer learning process will work using the command - ``$ bash train.sh``.
